--gutter:RegisterAllEvents()
--gutter:SetScript("OnEvent", function(self, event)
  --if event:sub(1, 4) == "UNIT" then return end
  --if event:sub(1, 4) == "GARR" then return end
  --if event:sub(1, 4) == "VOIC" then return end
  --if event:sub(1, 4) == "UPDA" then return end
  --if event:sub(1, 4) == "ACTI" then return end
  --if event:sub(1, 4) == "COMB" then return end
  --if event:sub(1, 4) == "CURS" then return end
  --if event:sub(1, 4) == "SPEL" then return end
  --if event:sub(1, 4) == "SKIL" then return end
  --if event:sub(1, 4) == "LFG_" then return end
  --if event:sub(1, 4) == "RECE" then return end
  --if event:sub(1, 4) == "CRIT" then return end
  --if event:sub(1, 4) == "GUIL" then return end
  --if event:sub(1, 4) == "BAG_" then return end
  --if event:sub(1, 4) == "TRAC" then return end
  --if event:sub(1, 4) == "CONS" then return end
  --if event:sub(1, 3) == "BN_" then return end
  --print(event)
--end)

-- fresh login
-- ADDON_LOADED
-- VARIABLES_LOADED
-- PLAYER_LOGIN
-- PLAYER_ENTERING_WORLD
-- LOADING_SCREEN_DISABLED

-- reload
-- ADDON_LOADED
-- VARIABLES_LOADED
-- PLAYER_LOGIN
-- PLAYER_ENTERING_WORLD
-- LOADING_SCREEN_DISABLED
